//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greewf.BaseLibrary.MVC.ChangeTracker.ChangeTrackerContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public AuditLog()
        {
            this.AuditLogDetails = new HashSet<AuditLogDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string EntityName { get; set; }
        public string EntityKey { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string UserId { get; set; }
        public string EventType { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AuditLogDetail> AuditLogDetails { get; set; }
        public virtual AuditLog Parent { get; set; }
    }
}
