//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greewf.BaseLibrary.MVC.ChangeTracker.ChangeTrackerContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChangeTrackerContext : DbContext
    {
        public ChangeTrackerContext()
            : base("name=ChangeTrackerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AuditLogDetail> AuditLogDetails { get; set; }
        public DbSet<AuditLog> AuditLogs { get; set; }
    }
}
