//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greewf.BaseLibrary.Logging
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    
    public partial class LogContext : DbContext
    {
        public LogContext()
            : base("name=LogContext")
        {
        }
    
    //    commented by moravej
    //    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    //    {
    //        throw new UnintentionalCodeFirstException();
    //    }
    
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<LogDetail> LogDetails { get; set; }
    }
}
