//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greewf.BaseLibrary.Logging
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class LogDetail
    {
    	
        
        public long Id { get; set; }
    	
        
        public long LogId { get; set; }
    	
        
        public string Key { get; set; }
    	
        
        public string KeyTitle { get; set; }
    	
        
        public string Value { get; set; }
    }
}
